### ISSUE TITLE
Data to add

### ISSUE THREAD

**Issue by jplatte** [jplatte/caniuse.rs#16]
It can be a somewhat time-intensive task to collect all the relevant data about a feature in addition to just keeping on top of what things are getting stabilized. This is my todo list of stuff that's been stabilized and I've been meaning to add. Maybe somebody wants to collect the data on some of these and create a PR?

- [ ] rust-lang/rust#72303
- [ ] rust-lang/rust#76119
- [ ] rust-lang/rust#77339
- [ ] rust-lang/rust#78578
- [ ] rust-lang/rust#80968
- [ ] rust-lang/rust#81107

**Comment by robjtede** [comment]
Had forgotten this existed. There's some things that have been addressed. Don't mind helping with this list if you're happy to give perms for editing issues.

**Comment by jplatte** [comment]
Updated a few things earlier but I'd be happy to let you update any other parts that you know to be outdated :)
